#!/usr/bin/env bash
# ------------------------------------------------------------------
#
#     Scripts/batperc
#     Description: Script for piping the battery status into dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

#BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}'`
#STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`
BAT=$(acpi -b | cut -d " " -f 4 | sed 's/%,//')
STATUS=$(acpi -b | cut -d " " -f 3 | sed 's/,//')

if [[ $BAT -lt 10 ]]; then
    ICON="bat_empty_02.xbm"
    BATBAR=`echo -e "^fg(red)$BAT"\
        | gdbar -bg "#393939" -fg red -h 1 -w 60`
    if [[ $STATUS != "Charging" ]]; then
        notify-send "Warning, battery level below 10 percent" -u critical -t 30000
    fi
else
    ICON="bat_full_02.xbm"
    BATBAR=`echo -e "$BAT"\
        | gdbar -bg "#393939" -fg "#d6d6d6" -h 1 -w 60`
fi

if [[ $STATUS != "Discharging" ]]; then
    ICON="ac.xbm"
fi
ICON="^i(${HOME}/.xmonad/dzen/icons/xbm8x8/$ICON)"
echo "$ICON $BATBAR"
