#!/usr/bin/env bash

background="#000000"
foreground="#CCCCCC"
highlight="#308888"
FONT=Terminus-8

XPOS=1450
YPOS=19
WIDTH="120"
HEIGHT="12"
LINES="12"

KBD=$(setxkbmap -query | tail -2 | head -1 | cut -d " " -f 6)

echo $KBD
#(echo $KBD; sleep 10) | dzen2 -fg $foreground -h $HEIGHT -bg $background -fn $FONT -x $XPOS -y $YPOS -w $WIDTH -l $LINES #-e 'leaveslave=exit;onstart=uncollapse,unhide;button1=exit;button3=exit'
